name: swpc-testbed
recipe: drupal9
config:
  php: '8.1'
  via: apache
  webroot: web
  database: mariadb
services:
  appserver:
    config:
      php: .lando.php.ini
    build_as_root:
      - apt-get update -y
      - apt-get -y install vim
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
tooling:
  swpc-build:
    description: Build the SWPC testbed site.
    cmd:
      - scripts/install.sh
    service: appserver
  swpc-restore-db:
    description: Reset your database.
    cmd:
      - scripts/db-reset.sh
    service: appserver

